version: '3.1'

services:
  payroll_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: payroll_elasticsearch
    restart: unless-stopped
    ports:
      - "9200:9200"
    volumes:
      - payroll_elasticsearch:/usr/share/elasticsearch/data
    networks:
      - payroll

  payroll_kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    container_name: payroll_kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://payroll_elasticsearch:9200
    depends_on:
      - payroll_elasticsearch
    networks:
      - payroll

networks:
  payroll:
    driver: bridge

volumes:
  payroll_elasticsearch:
